### ISSUE TITLE
Mentioning both M5x30 and M5x35 screws

### ISSUE THREAD

**Issue by jokogr** [cookiengineer/anet-a8-upgrades#11]
In the parts list M5x30 screws are being mentioned, while Section 1 mentions M5x35 screws. I guess both are equally fit since they are just here to tense the x-belt, but it could create some confusion to readers.

**Comment by cookiengineer** [comment]
Yes, you are right. I should mention that the x35 is the minimum length, so you can use x50 there as length (that's my setup).

**Comment by cookiengineer** [comment]
Fixed it. Reopen if it's still unclear :)

**Comment by jokogr** [comment]
Thanks for clearing this out, I had ordered M5x30 screws, I should get x50 ones :unamused:
