### ISSUE TITLE
4mm pneumatic adapter

### ISSUE THREAD

**Issue by jsmithgmail** [cookiengineer/anet-a8-upgrades#4]
Hi, this is a great tutorial.  What size thread is needed for the adapter, is it M6?

Will this adapter work?

https://www.amazon.com/Witbot-Straight-Fitting-Connector-Printer/dp/B01NANKRTD

**Comment by cookiengineer** [comment]
The small side of the pneumatic adapter is meant to fit into the motor block's hole where the extruder is screwed up in, too. The small diameter is 6mm (M6) while the bigger diameter is around ~9.5mm; but those are imperial measurements (as is all pneumatic tube stuff) so it is more likely sold as 3/8" (3/8 * 25.4 is 9.51mm).

**Comment by cookiengineer** [comment]
Added a note for this into the README, so that others don't have the same problem.
