### ISSUE TITLE
Print settings for upgrade parts

### ISSUE THREAD

**Issue by loidor** [cookiengineer/anet-a8-upgrades#8]
Not a biggie, but it would be super with some print settings suggestions for the upgrade parts. 

Most of them prints all right on a stock A8 with 0.2 layer height and 60mm/s speed, but I needed to lower the speed to 30mm/s on the X belt holder, and add a brim on the T corners in order for the thin parts to stay proper in place (that might be on me though, since I'm using PEI rather than the shipped painter's tape).

**Comment by cookiengineer** [comment]
Phew, not sure what I used back then, but I would print the smaller parts with 0.12mm precision and the bigger ones with 0.2mm. Typically I use tetrahedron / octagon infill at 90% and default speed settings and they worked fine in the past.

Did you replace the belts with better ones or did you use the shitty OEM plastic ones?

**Comment by loidor** [comment]
I got proper fiber glass reinforced ones.

Guess 0.12 would've worked even better than lower speed. Why not 0.1?For infill I used rectilinear at 80. Pretty much the same as honeycomb at 90, I believe.

**Comment by cookiengineer** [comment]
The stepper motors of the Anet can only vary in 0.4mm because they are not more precise in their degrees that they can do technically speaking, so 0.4, 0.8, 0.12, 0.24 etc. pp. is only possible, as 0.4 is the actual measurement of a single step in Z-direction.

**Comment by loidor** [comment]
Ah! Didn't know that.

Speaking of motors, although they're small they're still nema 17. There's a 5mm difference in the hole spacing, so 14s wouldn't fit the same holes as 17s :)

Do you want me to post a pull request with the edits? If so, I'll also measure what the max size of Z axis motors would be.

**Comment by cookiengineer** [comment]
Yes, I'd love to merge your changes in.

**Comment by cookiengineer** [comment]
Saw the PR, merged in. Thanks much!
